### ISSUE TITLE
savematrix() crashes kernel when trying to save object array

### ISSUE THREAD

**Issue by sestras** [groops-devs/groopsio#6]
Function `savematrix()` (and potentially others?) crash the kernel when you (accidentally) try to save an object array instead of a float array (e.g. date as datetime instead of MJD). No error message is given, thus the issue probably lies somewhere in the C++ part.

I can reproduce the issue reliably with this minimal example:
```python
import datetime as dt
import groops.io as gio
import numpy as np
gio.savematrix("test.txt", np.array([dt.datetime(2020,1,1)]))
```

**Comment by akvas** [comment]
Thanks for opening the issue. This is fixed in 25ba892e0f4e8deb79dac239d067412ba3091997. The function now throws an exception instead of silently segfaulting.

Cheers,
Andreas
