### ISSUE TITLE
CMake Error at CMakeLists When Installing groopsio on Windows Machine

### ISSUE THREAD

**Issue by Galatiy** [groops-devs/groopsio#8]
Greetings Patrick,

I am trying to install the groopsio on a Windows machine. However, I encounter a CMake Error as pointed out in the subject. The software is failing to identify the 'constants.cpp' in the base folder.  To my surprise, the path is correctly set in the environment variable.

I, therefore, wonder if you could advise on this matter. Please, find attached the log file for further details about the other associated errors.

Thanks for your understanding and support.

Regards,

Galatiya.
[groopsio_installation_error.log](https://github.com/groops-devs/groopsio/files/8255515/groopsio_installation_error.log)

**Comment by zhedumi** [comment]
Hi Galatiy,

I might need some additional info to find the source of the error. I presume you successfully installed [groops for windows ](https://github.com/groops-devs/groops/blob/main/INSTALL.md#microsoft-windows) and therefore have a running version of that and using the newest release available on the [github](https://github.com/groops-devs/groops).

From the log your groops source directory is: C:\Users\ABD\groops\source and I presume that is where you can find the groops source files. So that seems correct as you also noticed.

What is your gcc compiler version provided from Mingw? 
What python version are you using? And are you using a PIP virtual environment or a conda environment?

Best regards,

Patrick

**Comment by Galatiy** [comment]
Dear Patrick,

Many thanks for your response. 

On this computer, I have the newest version of GROOPS compiled on 13th March 2022. You may refer to the screen-shot below which also shows the gcc compiler version I am using:

![status_of_groops_and_gcc](https://user-images.githubusercontent.com/41967015/158533771-d96d4ee4-8d4f-4d03-bf52-04580d74a60f.PNG)

In the case of python and pip versions, I am using 3.10.2 and 22.0.4, respectively as shown in the figure below.

![pip_version](https://user-images.githubusercontent.com/41967015/158534370-94be6d9b-7d47-4e80-85ba-0fcfc4db428e.PNG)

I hope the information given above will assist in identifying the cause of the installation failure.

Thanks in advance and looking forward to your usual support.

Best regards,

Galatiya

**Comment by zhedumi** [comment]
Hi Galatiya,

I just run the test and got to the same issue on windows and python 3.10. A Quickfix which worked for me was to change the line within
CMakeLists.txt from
 https://github.com/groops-devs/groopsio/blob/0cd095be168cebc7f44fa86b8762dcf1c6997ca7/CMakeLists.txt#L27

To:
```
set(GROOPS_SOURCE_DIR "C:/groops/source")
```

Here is the changed CMakeLists.txt which I used
[CMakeLists.txt](https://github.com/groops-devs/groopsio/files/8271479/CMakeLists.txt)

I am still investigating as to why this occurs but please be kind to tell me if that quickfix also works for you.

Best regards,
Patrick

**Comment by Galatiy** [comment]
Hi Patrick,

Many thanks for your prompt response.

I have been trying to this problem with different Python versions but I could not succeed. Now, I have successfully installed the software using your revised CMakeLists.txt. Here is the evidence.

![successfully_installed_groopsio-0 1](https://user-images.githubusercontent.com/41967015/158684010-456c18db-7e02-4ff0-a1bd-1cb0221b6a2f.PNG)

Thanks for spending your time on this issue. 

Kind regards,

Galatiya

**Comment by akvas** [comment]
Hi @Galatiy and @zhedumi,

the default behavior of groopsio is to look in the user's home directory (on Windows this will be `C:\Users\NAME\groops\source`) for the GROOPS source files. This can be changed by setting the environment variable `GROOPS_SOURCE_DIR` to a different folder (e.g. `C:\groops\source`). In 4af0544b8820066fb6ee108bb7cd190cbabfd3a4 I have added instructions on how to do this in the Windows Command Prompt and PowerShell.

Cheers,
Andreas
